apiVersion: v1
kind: Service
metadata:
  name: {{ include "sre-helm.fullname" . }}
  labels:
    {{- include "sre-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.targetPort }} # Port on pod selected by this service expose
      targetPort: {{ .Values.service.targetPort }} # Port on pod selected by this service expose
      nodePort: {{ .Values.service.nodePort }} # Port on the node where service is available 
      protocol: TCP
      name: http
  selector:
    {{- include "sre-helm.selectorLabels" . | nindent 4 }}