replicaCount: 1

image:
  repository: lucsilv/challenger-itau
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "lucsilv"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  # Port on pod selected by this service expose
  targetPort: 8080 
  # Port on the node where service is available 
  nodePort: 30950 

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
limits:
  cpu: 100m
  memory: 128Mi
requests:
  cpu: 100m
  memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1